function [fitresult, gof] = createFit_infoSaturation(n, m)
%CREATEFIT(N,M)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : n
%      Y Output: m
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 14-Jan-2019 14:55:05


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( n, m );

% Set up fittype and options.
ft = fittype( 'I_0*x/(1+x/N)', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [1 100];
%opts.Lower = [0 0];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% % Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, xData, yData );
% legend( h, 'm vs. n', 'untitled fit 1', 'Location', 'NorthEast' );
% %Label axes
% xlabel n
% ylabel m
% grid on
% 

