MESSAGE = ['Running place decoding with shuffles, and shuffles on spoof, using'...
    ' GNB and ECOCSVM(linear, 1vsAll) on open field data, with traces filling using no regularization'...
    ' and using 4 train0.7/test0.3 splits, reporting average and sem'];

res = batch_place_decoding({'open_field'}, 'parloops', 4, 'msg', MESSAGE,...
    'pickup', 'TRACES_OPENFIELD');