ds_hpc = quick_ds('../cohort14_dual/c14m6/c14m6d10', 'deprobe', 'nocells', 'cm', 'hpc_cm01_fix');
ds_prl = quick_ds('../cohort14_dual/c14m6/c14m6d10', 'deprobe', 'nocells', 'cm', 'prl_cm01_fix');

alg = my_algs('linsvm', 0.1); %0.1 for L1 regularization

[X, ks] = ds_dataset(ds_prl,...
    'selection', 0.3,...
    'filling', 'box',...
    'trials', strcmp({ds_prl.trials.start}, 'west'),...
    'target', {ds_prl.trials.end});
[train_error_prl, test_error_prl, model, fitinf] =...
    evaluate_alg(alg,...
    X, strcmp(ks, 'north'),...
    'retain_models', true,...
    'retain_fitinfo', true,...
    'train_frac', 1);
[~, order] = sort(-abs(model.Beta));
order = order(1:nnz(model.Beta));
see = @(n) histogram2(X(:, n), strcmp(ks, 'north')', 10);