function [fitresult, gof] = createFit_logIMSE(ln, limse)
%CREATEFIT(LN,LIMSE)
%  Create a fit.
%
%  Data for 'logdomain' fit:
%      X Input : ln
%      Y Output: limse
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 17-Jun-2021 15:21:06


%% Fit: 'logdomain'.
[xData, yData] = prepareCurveData( ln, limse );

% Set up fittype and options.
ft = fittype( 'I0 + n - log(1+exp(n-N))', 'independent', 'n', 'dependent', 'I' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.0820008338757376 0.333023106085189];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'logdomain' );
h = plot( fitresult, xData, yData );
legend( h, 'limse vs. ln', 'logdomain', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'ln', 'Interpreter', 'none' );
ylabel( 'limse', 'Interpreter', 'none' );
grid on


