function [fitresult, gof] = createFit_intercept(n_neu, q)
%CREATEFIT(N_NEU,Q)
%  Create a fit.
%
%  Data for 'linimse' fit:
%      X Input : n_neu
%      Y Output: q
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 18-Jun-2021 12:08:37


%% Fit: 'linimse'.
[xData, yData] = prepareCurveData( n_neu, q );

% Set up fittype and options.
ft = fittype( 'I_0*n / (1 + n/N) + c', 'independent', 'n', 'dependent', 'I' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.001 50 0];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

%% Plot fit with data.
%figure( 'Name', 'linimse' );
%h = plot( fitresult, xData, yData );
%legend( h, 'q vs. n_neu', 'linimse', 'Location', 'NorthEast', 'Interpreter', 'none' );
%% Label axes
%xlabel( 'n_neu', 'Interpreter', 'none' );
%ylabel( 'q', 'Interpreter', 'none' );
%grid on


